USE [master]
GO
CREATE LOGIN [loja] WITH PASSWORD=N'loja', DEFAULT_DATABASE=[Loja], DEFAULT_LANGUAGE=[Português (Brasil)], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Loja]
GO
CREATE USER [loja] FOR LOGIN [loja]
GO
USE [Loja]
GO
ALTER ROLE [db_owner] ADD MEMBER [loja]
GO
